### ISSUE TITLE
Dropdown list is scrolling when hovering over the last visible item

### ISSUE THREAD

**Issue by tstoik** [sagalbot/vue-select#1028]
**Describe the bug**
When hovering over the last visible item in the dropdown, the list begins to automatically scroll without user action. 

**To Reproduce**
1. Open dropdown
2. Hover individual items as you make your way down the list.
3. As you over over the last visible item in the list, especially if it is partially visible, the list start scrolling rapidly to the bottom

https://cl.ly/a0e39463867c

In the video linked above, I am not using the scrollwheel or taking any action that would cause the list to scroll, yet it scrolls whenever I hover over the last visible item. 

**Expected behavior**
Ability to hover over all items without triggering scrolling. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser: Firefox 71 & Chrome 79

**Comment by ccartrec** [comment]
try replacing method maybeAdjustScroll()
    ```
maybeAdjustScroll() {
        const pixelsToPointerTop = this.pixelsToPointerTop();
        const pixelsToPointerBottom = this.pixelsToPointerBottom();

        if (pixelsToPointerTop <= this.viewport().top) {
            return this.scrollTo(pixelsToPointerTop);
        } else if (pixelsToPointerBottom >= this.viewport().bottom) {
            return this.scrollTo(pixelsToPointerBottom - (this.viewport().bottom - this.viewport().top));
        }
    }
```

**Comment by opassion** [comment]
@ccartrec does this mean I need to fork this and fix it myself?

**Comment by ccartrec** [comment]
@opassion yes=) you will find maybeAdjustScroll() in pointerScroll.ts and replace on this

**Comment by andreasvirkus** [comment]
@opassion you could also extend the component and override the method

https://github.com/sagalbot/vue-select/issues/449
