### ISSUE TITLE
Autocomplete prop accepts a value but is not bind to input.

### ISSUE THREAD

**Issue by jaskaran-kalra** [sagalbot/vue-select#1035]
In Select.vue there is a prop autocomplete, but that value is not bind to input element.

![image](https://user-images.githubusercontent.com/14268899/71829259-3ccfcd80-30ca-11ea-9104-9341f3b1593c.png)

Select.vue is accepting a prop "autocompelete" but for the input autocomplete is hardcoded to "off", which creating issues in chrome. 
I wanted to set a custom autocomplete value.

![image](https://user-images.githubusercontent.com/14268899/71829444-ab149000-30ca-11ea-9e6b-92bfcb160243.png)

Temporarily i am using the follwing code to resolve my issue

`this.$refs.select.$el.querySelector('input').autocomplete = 'new-password';`

**Comment by ewerkema** [comment]
Same issue here, autocomplete `off` is [not working anymore](https://stackoverflow.com/a/29582380).
