### ISSUE TITLE
In IE, clicking the scrollbar collapses the dropdown

### ISSUE THREAD

**Issue by pascallaliberte** [sagalbot/vue-select#106]
Tested in IE 10, IE 11:

When clicking on the scrollbar of the dropdown menu, the dropdown collapses unexpectedly. See the gif:

![vue-select-scrollbar-ie](https://cloud.githubusercontent.com/assets/104179/20146558/6734ae46-a672-11e6-960b-7186fb90402b.gif)

**Comment by pascallaliberte** [comment]
I'm running into a similar issue elsewhere, so I hope this helps debug it: in IE, clicking a scroll bar will bubble up a click event further up the parent chain. Maybe there's a way to limit the click's reach, but I haven't found one yet.

**Comment by wa05** [comment]
Same problem in Chrome...

**Comment by Saul3d** [comment]
I'm not seeing this problem in chrome but does anyone have a temporary fix for this issue in IE

**Comment by andremiguelaa** [comment]
Any news on this issue?

**Comment by eckledes** [comment]
Is this bug fixed in Release 2.3.0?

**Comment by adi518** [comment]
@eckledes No.

**Comment by adi518** [comment]
Okay, should be fixed now: #373

**Comment by korobkadima** [comment]
same problem on Chrome in modal window

**Comment by nahuelhds** [comment]
I'm on v2.5.1 and this keeps happening. In my case, only the first time I try to scroll with native browser UI after doing an ajax search with brings me lot of results. Once closed, if I open the dropdown again then I can scroll using the native browser UI.
