### ISSUE TITLE
If value is false not showing text 

### ISSUE THREAD

**Issue by SeyyedKhandon** [sagalbot/vue-select#1138]
First of all thank you for this great component.
the problem is when you use true false for select options, it wont show the false value and it seems there is no way to use it for boolean case :

```
Vue.component('v-select', VueSelect.VueSelect)

new Vue({
  el: '#app',
  data: {
    options: [true, false]
  }
})

```
```
<div id="app">
  <h1>Vue Select</h1>
  <v-select :options="options"></v-select>
</div>
```

**Comment by miyakoj** [comment]
I've run into the same problem. My options were set as an array of objects. It also won't select false even if it's the initial value. My workaround was to use strings instead.
