### ISSUE TITLE
Broken keyboard navigation through options

### ISSUE THREAD

**Issue by inoric** [sagalbot/vue-select#1161]
**Describe the bug**
Selecting options using up/down arrows always jumps to first and last items, skipping everything in between.

**To Reproduce**
1. Open the dropdown with 3 or more selectable options
2. Press down key: the last item will be selected
3. Press up key: the first item will be selected

**Expected behavior**
Moving through options with arrow keys should select next/previous items, not jump to first/last.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox 75
 - Version: 3.10.0

**Additional context**
Seems to be broken in commit 2eb39087fde4712ba1c5e5d82ae68bf0e3270c57.
break statements were removed from typeAheadDown() and typeAheadUp() functions in src/mixins/typeAheadPointer.js. Looks like an accident while removing maybeAdjustScroll.

**Comment by mix3d** [comment]
I tried to create a PR for this, but I'm having a hell of a time getting the code to run on my machine :/
Your missing `break` comment is likely correct, however.

**Comment by inoric** [comment]
Just made a pull request. I rarely contribute to other repos, hope I didn't mess up.

@mix3d I had some trouble running the serve command due to fuse.js, which is required for the test page used in "serve" command but isn't listed in dev dependencies. Not sure if there is something I was doing wrong.

**Comment by mix3d** [comment]
I figured it out. The /docs folder has its own package.json, but it has a bad version number (not 3 part semver), preventing `npm install` from working.  I was able to test and confirm that it is working by adding in back the `break;`

**Comment by mix3d** [comment]
For some reason, I couldn't use the built file in project though.. not sure what I was doing wrong.
