### ISSUE TITLE
The reduced value is shown instead of the label.

### ISSUE THREAD

**Issue by jamesrgriffiths** [sagalbot/vue-select#1186]
I'm sure I'm doing something wrong here, but I can't seem to find it. I have a select for users, with additional options for "ALL" and "None". For this I thought it would be easiest to have an array of objects with 2 values: id and name. In my controller I build the object like this:

`$users[] = (object)["id" => 0, "name" => 'ALL'];
 $users[] = (object)["id" => -1, "name" => 'NONE'];
 foreach(UserFacade::getAll('name') as $obj_user) { $users[] = (object)["id" => $obj_user->id, "name" => strtoupper($obj_user->name)]; }`

That seems fine and I'm able to bring my array into a vue variable called users. I also have a user variable with a default of 'ALL'. And here is my vue-select:

`<v-select :options="users" v-model="user" :reduce="user => user.id" label="name"></v-select>`

It initially looks fine, all of the options show by name in the list and it displays 'ALL' as the selected option. Then when I select a different option I have a vue watch that fires off to get the updated data. That also works properly and updates the selected item, only it shows the selected item by id instead of name. The other options in the list are still shown by name, and when I select 'ALL' again it shows 'ALL'. But if for instance I select 'NONE' it show -1 (and everything else works as expected).

Any ideas on what I might be doing wrong?

**Comment by Extrapolator214** [comment]
@jamesrgriffiths I encountered the same problem, here is my workaround (with your example)

```vue
<v-select v-model="user"
          label="name"
          :options="users"
          :reduce="x => x.id"
>
  <template #selected-option="value">
    {{ setSelectedOption(users, value) }}
  </template>
</v-select>

methods: {
      setSelectedOption (options, value) {
        const option = options.find(x => x.value.toString() === value.label)
        return option.label
      }
}
```

As I see it, the problem is that the reduced value is represented as `{label: selected_user_id}`, so you need to manually search for the correct option object

**Comment by jamesrgriffiths** [comment]
@Extrapolator214 Thanks for this, I ended up going with a simpler select structure because I realized I didn't need all of the features for this project, but I'll keep this in mind for future reference.

**Comment by JordashTalon** [comment]
I'm having this same issue, is there a better way to solve this? Would expect that the label would show instead of the reduced value.

**Comment by Quang-Dong** [comment]
> 
> 
> @jamesrgriffiths I encountered the same problem, here is my workaround (with your example)
> 
> ```
> <v-select v-model="user"
>           label="name"
>           :options="users"
>           :reduce="x => x.id"
> >
>   <template #selected-option="value">
>     {{ setSelectedOption(users, value) }}
>   </template>
> </v-select>
> 
> methods: {
>       setSelectedOption (options, value) {
>         if(value.value === undefined){
>           const option = options.find(x => x.value.toString() === value.label)
>           return option.label
>         } else {
>           return value.label
>         }
>       }
> }
> ```
> 
> As I see it, the problem is that the reduced value is represented as `{label: selected_user_id}`, so you need to manually search for the correct option object

i just add  >:reduce="x => x.id". and it's work, thank you so much,
