### ISSUE TITLE
How to set loading property in infinite scroll dropdown

### ISSUE THREAD

**Issue by pranavkumar389** [sagalbot/vue-select#1189]
**Context:** I am making Axios call to fetch 10 records at a time. And I have implemented infinite scroll for the dropdown.

**Problem:** While the list is getting fetched the `no-option` slot works and displaying some text like "No options found" with the loader. It's not a  good idea to show both "no-option" text and the loader. Though we have some option(which is being fetched) we are showing "no-option" text.

**Question:** How to set loading property in infinite scroll dropdown while calling onOpen, or making the API calls?

**Comment by fkranenburg** [comment]
Try this:

```
    <template #no-options="{ searching, loading }">
      <div
        v-if="!loading"
      >No options</div>
    </template>
```
