### ISSUE TITLE
option slot

### ISSUE THREAD

**Issue by valeriy-efimov** [sagalbot/vue-select#1199]
```
<template>
  <v-select multiple :options="books" label="title">
    <template #option="{ title, author }">
      <h3 style="margin: 0">{{ title }}</h3>
      <em>{{ author.firstName }} {{ author.lastName }}</em>
    </template>
  </v-select>
</template>
```
Is it possible to change the class for the selected elements here?

like
`<h3 v-bind:class="{'text-green': isSelected}" style="margin: 0">{{ title }}</h3>`

**Comment by CHEWX** [comment]
Here — https://vue-select.org/api/slots.html#selected-option

**Comment by titusdecali** [comment]
This should probably be listed under `slots` in the docs as well
