### ISSUE TITLE
[fixed by myself] Selected option from v-mode is not highlighted in the menu

### ISSUE THREAD

**Issue by sebolio** [sagalbot/vue-select#1217]
**Describe the bug**

I have 2 options, the second one is selected from code but it keeps highlighting the first one.

`Administracion` is selected but `Principal` gets highlighted:
![image](https://user-images.githubusercontent.com/197329/85338292-fe7b6e80-b4af-11ea-8f35-7f8e3955a662.png)

Code:
```html
<v-select :options="tenants" label="name" v-model="currentValue"/>
```
```js
this.tenants =  [
    { "name": "Principal", "id": "W9wU7RcpkLaZ0VZjLwV7" },
    { "name": "Administracion", "id": "admin" } 
]
```

I have tried 3 ways:
```js
this.currentValue = {name:'Administracion', id: 'admin'}  //way 1
this.currentValue = 'Administracion' //way 2
this.currentValue = 'admin' //way 3
```
All these ways lead to the same result. 3rd way makes it show "admin" instead of "Administracion"

Latest Chrome in latest macOS with latest VueJS 2.x

**Comment by rossjcooper** [comment]
Have you tried adding `:reduce="tenant => tenant.id"` and the set `currentValue = "admin"` ?

**Comment by sebolio** [comment]
> Have you tried adding `:reduce="tenant => tenant.id"` and the set `currentValue = "admin"` ?

thanks for your suggestion, but it doesn't change the highlighting behavior, it just simplifies the usage (working with the id instead of the entire object), the problem is only visual, it visually highlights the first item instead of the actually selected

**Comment by sebolio** [comment]
whatever, i ended up fixing it by force using events
```html 
... v-on:search:focus="fixHighlight" />
```

```js
    fixHighlight () {
      this.$nextTick(_ => {
        $('.vs__dropdown-option.vs__dropdown-option--highlight').removeClass('vs__dropdown-option--highlight')
        $('.vs__dropdown-option.vs__dropdown-option--selected').addClass('vs__dropdown-option--highlight')
      })
    }
```
