### ISSUE TITLE
Updating those options values 

### ISSUE THREAD

**Issue by murilolivorato** [sagalbot/vue-select#125]
Hello my friend , thanks for sharing this code with us .
I have a question for you , I am trying to load the options values of the select from database and select those values , I am loading with axios , I updated the data() , but it is not refreshing the selection .

Do you have any example there that you load those data options from database ? do I need to make some comand to sellection ,like a update  command ? 

Thanks

**Comment by toastyblast** [comment]
How did you solve this issue? I'm using XMLHTTP and when I log options after my request, it says it's there, but the selection's not updating.
