### ISSUE TITLE
V-Select is not visible.

### ISSUE THREAD

**Issue by prashant1k99** [sagalbot/vue-select#1261]
**Describe the bug**
When we load the page the v-select is not visible.

**To Reproduce**
1. Create v-select using AJAX request

**Expected behavior**
The component should be visible as soon as the view is rendered.

**Screenshots**
![](https://raw.githubusercontent.com/prashant1k99/testing-graphql/master/v-select%20err.png)

**Code**
```js
<v-select name="category" :reduce="options => options._id" label="name" :options="listCategories" v-model="product.category">
  <template v-slot:option="option">
    {{ option.name }}
  </template>
</v-select>
```

**Comment by CadeBrown** [comment]
I am also having this problem; the element is created, but nothing renders and it has a size of zero in the browser. I assume it's my own ignorance

**Comment by prashant1k99** [comment]
I found the temporary solution to that (Not suggested). Render component after the data is fetched. @CadeBrown
