### ISSUE TITLE
How i can prevent clear input on focus

### ISSUE THREAD

**Issue by rustam87** [sagalbot/vue-select#1265]
I can search phrase few times, but when i click on input i need type phrase again
How to prevent it?
Thanks

**Comment by akuales** [comment]
have you ever found a solution for that?

**Comment by rustam87** [comment]
Yes, 

> have you ever found a solution for that?

Yes. I use cool-select .but cool select has some problem too.

**Comment by justfry** [comment]
<vSelect
....
ref="autocomplete"
@search:focus="$refs.autocomplete.search = value"
/>
