### ISSUE TITLE
Tab over Vue-Select with selected element then sets first option

### ISSUE THREAD

**Issue by danx-dev** [sagalbot/vue-select#1322]
When i have selected an element in the vue-select and then again tab over the vue-select it change selected to the first element in list.
How to make my selected element highlighted when i tab over it ?

https://codepen.io/danx-dev/pen/gOwpPYp

Reproduce:
Target first input box
Tab once
Search for Denmark
Select with Tab
Target first input box
Tab again 
Tab again
Now selected has change to Afghanistan

**Comment by danx-dev** [comment]
I made a workaround for this
by setting typeAheadPointer to correct index on close event.
https://codepen.io/danx-dev/pen/JjRdOyM

**Comment by nhsajib** [comment]
> I made a workaround for this
> by setting typeAheadPointer to correct index on close event.
> https://codepen.io/danx-dev/pen/JjRdOyM

### **This is not working for me.**

**Comment by danx-dev** [comment]
nhsajib can you describe your flow ?

**Comment by nhsajib** [comment]
<div class="form-group" id="sell_ledger">
    <label for="ledger" class="mb-0">Ledger</label>
    <v-select
        :options="ledgers"
        label="company"
        v-model="sale.ledger"
        :selectOnTab="true"
        >
        <template #search="{attributes, events}">
        <input
            id="ledger"
            class="vs__search"
            :required="!sale.ledger"
            v-bind="attributes"
            v-on="events"
        />
        </template>
    </v-select>
</div>

**Comment by nhsajib** [comment]
@danx-dev 

https://codepen.io/nhsajib/pen/jOMyQNq

**Comment by nhsajib** [comment]
@danx-dev now works fine. 
this not work with <template #search="{attributes, events}">
