### ISSUE TITLE
Using object in label

### ISSUE THREAD

**Issue by kossa** [sagalbot/vue-select#1352]
I'm using Laravel with multi language so all my categories.name are saved as json, something like : `{en:"english name", en:"arabic name"...}`

when I try this code : 
```
<v-select required label="name" :options="categories" v-model="category" placeholder="Choose a category ..."></v-select>
```

I got :
![image](https://user-images.githubusercontent.com/1175584/104835222-77f00980-58a5-11eb-877e-42e024dbbdea.png)

And when I try `name.en` like : 
```
<v-select required label="name.en" :options="categories" v-model="category" placeholder="Choose a category ..."></v-select>
```
I got:
![image](https://user-images.githubusercontent.com/1175584/104835239-935b1480-58a5-11eb-883a-9e5956770096.png)

**Comment by romain-lgr** [comment]
Use `getOptionLabel`:

ie. `<v-select :getOptionLabel="opt => opt.name.en" />`

**Comment by kossa** [comment]
Thank you @romain-lgr
