### ISSUE TITLE
Error when running with vite.js

### ISSUE THREAD

**Issue by rrrrando** [sagalbot/vue-select#1395]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `vue-select@3.11.2` for the project I'm working on.

When using vitejs with the vue3-compat branch of vue-select i ran into and error. Apperantly vite doesn't like imports without file extensions.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/vue-select/src/components/childComponents.js b/node_modules/vue-select/src/components/childComponents.js
index ab01201..4ac6b4f 100644
--- a/node_modules/vue-select/src/components/childComponents.js
+++ b/node_modules/vue-select/src/components/childComponents.js
@@ -1,5 +1,5 @@
-import Deselect from './Deselect';
-import OpenIndicator from './OpenIndicator';
+import Deselect from './Deselect.vue';
+import OpenIndicator from './OpenIndicator.vue';
 
 export default {
   Deselect,
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by MatthijsBe** [comment]
I have the same Issue when I want to use it with Single-spa, this will fix the error.
