### ISSUE TITLE
:selectable is sometimes ignored

### ISSUE THREAD

**Issue by Anatta336** [sagalbot/vue-select#1416]
**Describe the bug**
Under certain circumstances the `selectable` attribute is ignored when using text to filter the options.

**To Reproduce**
1. Open this example: https://codepen.io/anatta336/pen/YzNMONg
2. Select "Block of wood" and click the "exclude" button.
3. Select "Plank of wood" and click the  "exclude" button.
Both items in the select element should now be excluded. The `v-select` element correctly shows them greyed out, and they cannot be selected.
4. Type "wood" into the select element, and press enter.
The "Block of wood" item will be selected, despite not being selectable.

**Expected behavior**
No item should be selected.

**Desktop**
 - OS: Windows 10 (64-bit)
 - Browser: Tested with Firefox 88.0 (64-bit), Chrome 90.0.4430.93 (64-bit)

**Additional context**
The issue only occurs with some types of selectable criteria. It doesn't happen with simpler tests such as `return false;` or `return product.id > 10;`. I've not been able to find cases that cause the issue other than those very similar to the attached example.

The issue only occurs when there's multiple results when typing, and they're all not selectable.

**Fix**
I don't know this project's code well enough to know if this is the best approach, but adding a `this.selectable` check to the following line appears to resolve the issue.
https://github.com/sagalbot/vue-select/blob/2f18243d0ad7225d266a17f09b5b3c43c59079e5/src/mixins/typeAheadPointer.js#L56
```js
if (typeAheadOption && this.selectable(typeAheadOption)) {
```

**Comment by schen-10x** [comment]
I have the same issue in 3.11.2 release, and reported in #1419.  In my case, my select component is not multi select.
