### ISSUE TITLE
Option not selectable can still be selected via search & enter key

### ISSUE THREAD

**Issue by schen-10x** [sagalbot/vue-select#1419]
**Describe the bug**
An option that is not  selectable can still be selected via search and press the enter key. 

**Additional context**
Upon debugging the typeAheadPonter.js,  the typeAheadPointer is first initialized to -1,  but after that, it's always set to 0, never reset back to -1.  And thus in the typeAheadSelect(), the typeAheadOption will be the the matching filtered option, even if it's not selectable. 
Suggest changing line 56: if (typeAheadOption) --->  if (typeAheadOption && this.selectable(typeAheadOption))

**Comment by viperet** [comment]
@schen-10x can confirm this bug, it only reproducible with the last item in the list for me. Thanks a lot for the suggested fix!

**Comment by avandrevitor** [comment]
I'm having the same problem, any idea how to solve it?

**Comment by schen-10x** [comment]
For now I check each option when it's selected to see if it can be
selected, for example:
   <v-select :options=*"getOptions"* id=*"source"* :class=*"'col-6'"*

            v-model=*"inventory.source"* append-to-body

                    placeholder=*"Select a Source"*

                    :selectable=*"(option) => isSourceSelectable(option)"*

                    @option:selected=*"sourceSelected"*

                    >

                    <template #search=*"{attributes, events}"*>

                        <input

                        class=*"vs__search"*

                        v-bind=*"attributes"*

                        v-on=*"events"*

                        :required=*"!inventory.source"*

                        />

                    </template>

            </v-select>

 in the component's methods:
 *sourceSelected*(option) {

         //need to do this until vue-select fix its issue #1419

         *if* (!*this*.isSourceSelectable(option)) *this*.inventory.source
= *null*;

      },

  *isSourceSelectable(option)*(option) {

         //console.log("option is->", option);

         //todo return true or false

      },




Hope this helps.

Shao
