### ISSUE TITLE
@Kalifr use the beta channel for vue-select `"vue-select": "^4.0.0-beta.1",` works fine for me. Be sure to upgrade to vue: 3.2.x

### ISSUE THREAD

**Issue by Archetipo95** [sagalbot/vue-select#1546]
This is not working, I'm trying to change icons. I tryed with svg and emoji. Can someone help me or give me a working example?

@Kalifr use the beta channel for vue-select `"vue-select": "^4.0.0-beta.1",` works fine for me. Be sure to upgrade to vue: 3.2.x

btw, for anyone overriding default components => 
- In the vue3 beta version use:
```JS
import vSelect from "vue-select";
vSelect.props.components.default = () => ({
  Deselect: CloseIcon, // CloseIcon and CaretDownIcon are vue components with svg inside of them
  OpenIndicator: CaretDownIcon,
});
```
Instead of:
```JS
import vSelect from "vue-select";
vSelect.props.components.default = () => ({
  Deselect: {
    render: (createElement) => createElement(CloseIcon),
  },
  OpenIndicator: {
    render: (createElement) => createElement(CaretDownIcon),
  },
});
```

_Originally posted by @mathiash98 in https://github.com/sagalbot/vue-select/issues/1251#issuecomment-982545832_

**Comment by mathiash98** [comment]
As I wrote: `CloseIcon and CaretDownIcon are vue components`

Put your svg and or emoji inside a Vue Component

**Comment by Archetipo95** [comment]
Yep it worked, I think I was importing the wrong 😑 file...
