### ISSUE TITLE
Not possible to override search?

### ISSUE THREAD

**Issue by SashaRyder** [sagalbot/vue-select#1573]
**Describe the bug**
Attempting to handle searching myself due to having the same issue as https://github.com/sagalbot/vue-select/issues/1560, but i'm still getting said error 

**To Reproduce**
Attempt to search with a lot of items, it breaks, see above linked issue

**Expected behavior**
It not to break

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Brave

**Comment by SashaRyder** [comment]
I've fixed this by doing the following:

```
<v-select :getOptionKey="(opt) => getOptionKey(opt)"
```

With the method

```
getOptionKey(option) {},
```

Probably not the best fix but its fixed for me now

**Comment by fareesh** [comment]
Is this still the best way to handle this scenario?
