### ISSUE TITLE
When using ajax to search for data, the drop-down option does not appear for the first time

### ISSUE THREAD

**Issue by 8debug** [sagalbot/vue-select#1610]
> Please respect maintainers time by filling in these sections. Your issue will likely be closed without this information.

- Vue Version: 2.6.14
- Vue Select Version: 3.18.3

**Describe the bug**
When using the ajax method to manually enter the search criteria, there is no data in the first drop-down item, But the return value of ajax has data
![image](https://user-images.githubusercontent.com/3394927/157423080-ce954f8c-9f42-4fe0-a8eb-5c759a822a32.png)

The drop-down list only appears when the search criteria are removed
![image](https://user-images.githubusercontent.com/3394927/157423270-fbb638c0-693f-4265-9250-26fd8937f965.png)

**Reproduction Link**
A link to a reproduction of the bug. This is a huge help.

**Steps To Reproduce**
Outline the steps to reproduce the bug.

**Expected behavior**

**Screenshots**

**Comment by AndhikaR** [comment]
mind to explain how to fix this?

**Comment by IKKaybe** [comment]
Im also having this issue. Any fix?
