### ISSUE TITLE
Error using new beta

### ISSUE THREAD

**Issue by goldalworming** [sagalbot/vue-select#1677]
![image](https://user-images.githubusercontent.com/440256/186084080-acb4776c-b85f-4059-a1bf-0409234411ac.png)

it's now critical problem in my place because I use CI/CD, the library make build failed, please fix ASAP 

@chamberlainpi

**Comment by elzodxon** [comment]
same problem.

**Comment by elzodxon** [comment]
I was having this issue and i used "trick". I just copied css and pasted into my styles. I know, it is not a good way but, for now, it is working XD

**Comment by goldalworming** [comment]
It works, thanks

**Comment by gllmp** [comment]
encountered the same issue in CI at build stage today, might be worth keeping the issue as openned until the beta is fixed

**Comment by chamberlainpi** [comment]
Why am I mentioned? 😕
