### ISSUE TITLE
@input No longer working in the Vue3 Beta Version

### ISSUE THREAD

**Issue by JordashTalon** [sagalbot/vue-select#1695]
> Please respect maintainers time by filling in these sections. Your issue will likely be closed without this information.

- Vue Version: Vue 3
- Vue Select Version: ^4.0.0-beta.5

**Describe the bug**
@input is no longer firing

**Steps To Reproduce**
Use @input="onInput()" the onInput() is never fired.

**Expected behavior**
When the v-model is changed the @input function is fired.

This was working in Vue2 but not the Vue3 beta.  I was able to get a change event working with the @option:selected event but @input no longer works.  @option:selected also doesn't handle when the clear x button is clicked.

**Comment by hainguyenhd** [comment]
You can use 
<v-select v-model="value" :options="options" **@option:selected="selectedHandle"**>

**Comment by hainguyenhd** [comment]
More: 
    "@open",
    "@close",
    "@update:modelValue",
    "@search",
    "@search:compositionstart",
    "@search:compositionend",
    "@search:keydown",
    "@search:blur",
    "@search:focus",
    "@search:input",
    "@option:created",
    "@option:selecting",
    "@option:selected",
    "@option:deselecting",
    "@option:deselected"

**Comment by JordashTalon** [comment]
Thanks @hainguyenhd `@update:modelValue` is the one that worked best for me, that also handles the case when the value is cleared.
