### ISSUE TITLE
Disabled Property dysfunctional in V4.0.0-beta.5

### ISSUE THREAD

**Issue by ManuelTS** [sagalbot/vue-select#1702]
- Vue Version:  3.2.21
- Vue Select Version: 4.0.0-beta.5

**Describe the bug**
Disabled is not working, the component remains fully functional when the [disabled prop](https://vue-select.org/api/props.html#disabled) is set to `false`.

**Steps To Reproduce**
I imported and set the VSelect as follows:

```
// ...
import vSelect from 'vue-select';
import CloseIcon from '@/components/CloseIcon.vue';
import CaretDownIcon from '@/components/CaretDownIcon.vue';

vSelect.props.components.default = () => ({
  Deselect: CloseIcon, // CloseIcon and CaretDownIcon are vue components with svg inside of them
  OpenIndicator: CaretDownIcon
});

const app = createApp(App)
  .use(createPinia())
  .use(instrumentation)
  .use(initRouter())
  .use(i18n)
  .use(PrimeVue, {
    locale: messages.de.primevue
  })
  .use(ToastService)
  .use(ConfirmationService);
app.mount('body');
app.component('VSelect', vSelect);
```
and in my SFC I just do:

```
    <VSelect
      label="value"
      :options="getTechnicianOptions()"
      :disabled="false"
      :placeholder="$t('action.choose')"
      @option:selected="technicianSelection($event, index)"
    ></VSelect>
```
in the template and I have

```
import 'vue-select/dist/vue-select.css';
```
in the scripts file. The `getTechnicianOptions()` just gives entries, nothing more.

**Expected behavior**
When disabled is set to false:
- The component is not functional
- Grayed out text with not allowed cursor on hover #1449
- Does not show the drop down icon #763

**Comment by SaschaMendel** [comment]
I think you might have gotten it backwards (maybe i am missing something)
you want  disabled to be true to disable the component
