### ISSUE TITLE
Using v-select with Vue 3 inside modal

### ISSUE THREAD

**Issue by AbakusToTheMoon** [sagalbot/vue-select#1810]
### Discussed in https://github.com/sagalbot/vue-select/discussions/1809

<div type='discussions-op-text'>

<sup>Originally posted by **AbakusToTheMoon** December  5, 2023</sup>
Hello,

I hope this message finds you well. I am currently using the beta version of the v-select package with Vue 3 in my project. While integrating it into a modal, I encountered an issue where the dropdown list remains confined within the modal container and does not extend beyond its boundaries.

As a result, when the list is longer than the modal height, I am unable to see the entire dropdown list as it gets cut off within the modal. This behavior is impacting the usability of the v-select component in modal, where it is essential to have the complete dropdown list visible.

Is the issue described here : [issue 136](https://github.com/sagalbot/vue-select/issues/136)

Thank you for your time and assistance.

Best regards,</div>

**Comment by Dodje** [comment]
Did you try appendToBody?

**Comment by AbakusToTheMoon** [comment]
Is it possible to have more information about 'appendToBody'?

**Comment by Dodje** [comment]
https://vue-select.org/api/props.html#appendtobody
The prop makes your list appended to body instead of original "relative" parent

**Comment by AbakusToTheMoon** [comment]
Thanks it's working !

I close the issue
