### ISSUE TITLE
Vue [warn] rendered virtual DOM tree is not matching server-rendered content

### ISSUE THREAD

**Issue by lmj0011** [sagalbot/vue-select#183]
this lib needs linting, VueJS v2 will throw this warning when I include `vue-select` in my project

![bad_syntax](https://cloud.githubusercontent.com/assets/9396189/24837637/45aad752-1cfe-11e7-8dac-2c75fef31e63.png)

**Comment by lmj0011** [comment]
![better_pic](https://cloud.githubusercontent.com/assets/9396189/25567955/203beabc-2dbe-11e7-9f14-4edac757735d.png)

**Comment by FabianEllenberger** [comment]
+1,  I'm facing the same issue, integrated `vue-select` as a plugin in my `nuxt` project. The markup seems fine to me when I inspect it, but the `[Vue-warn]` doesn't dissapear :-(

**Comment by Jones-S** [comment]
+1. Same problem here

**Comment by msahajwani** [comment]
+1. I am facing the same issue as well. Looking forward to a solution.
