### ISSUE TITLE
How do I select a previously saved value when the options are loaded via ajax?

### ISSUE THREAD

**Issue by sjordan1975** [sagalbot/vue-select#206]
I've previous received help with https://github.com/sagalbot/vue-select/issues/177 I'm grateful!

Now my use-case has expanded. How do I select a previously saved value when the options are loaded via ajax?

For example, borrowed from the countries example in the documentation...

`<v-select :value="syncedVal" :options="countries"></v-select>`

If rather than having a list of countries hardcoded as an array in my parent component, I do something like fetch the list of countries from a database via ajax when the component is mounted (using the mounted event).

NOTE: In my case, the countries array is not a simple array but rather an array of objects (similar is design to the issue mentioned in https://github.com/sagalbot/vue-select/issues/177:

```
[
{
id: 1,
label: 'Australia'
},
{
id: 2,
label: 'Canada'
},
{
id: 3,
label: 'Japan'
}
]
```

In my parent component I want to set syncedVal to '1' and then once the countries are populated via the ajax call, Canada should be selected.

Thank you

**Comment by sjordan1975** [comment]
I figured it out

**Comment by kulwinderseraphic** [comment]
Hi, @sjordan1975  Can you please share the solution. Thanks in advance.
