### ISSUE TITLE
on change issue

### ISSUE THREAD

**Issue by jagasan** [sagalbot/vue-select#265]
i used two v-select in one component with on-change event when i select one option value then it trigger both on-change method means execute both method  at time  onChangeClient() and addPledge() , so
how to solve call to execute only one  method which are selected 
 one more thing on-change event are execute two time  and also page load time also execute on change method

` <v-select placeholder="Select Client" v-model="selectedClient" :options="optionClients" :on-change="onChangeClient()"></v-select>
                 </div>
                 <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12" >
                   <v-select placeholder="Scenarios" v-model="selectedScenarios" :options="optionScenarios" :on-change="addPledge()"></v-select>
                 </div>`

`
    methods:{
      addPledge(){
        console.log("call on change addPledge------------");

            $('#ScenariousModal').modal('show');

      

      },
      onChangeClient(){
      
        console.log("call on change clinet------------");

      }
    }`

**Comment by darkopetreski** [comment]
The question is not very clear. It seems that you may have other problem. If you have two separate v-select elements, with different `on-change` function, they will execute the corresponding function. it is highly unlikely that  both of them will be executed in same time.
