### ISSUE TITLE
Emit Event on Deselect?

### ISSUE THREAD

**Issue by geraldbiggs** [sagalbot/vue-select#272]
I've successfully wired in a multiple select box to vuex via @input. However, multiple select boxes have a unique event maybe called, "deselect" or "remove." 

In my use case, when a user selects an option - vuex loads the selection up and builds up a list with new properties added. At the present moment, I'd have to run a test to see what values changed by comparing the payload vue-select sends, with the existing state in vuex both to prevent an overwrite, and to qualify removing something from the state.

To simplify things, I believe emitting a "deselect" or "remove" event with both the index (in the case of an array), and label (in the case of an object key by label) would greatly help.

**Comment by tiagoroldao** [comment]
@sagalbot Would you be open to a PR on this? I see this as related to #1005 but feel there would no issue adding the `option:selected` / `option:deselected` in V3?
