### ISSUE TITLE
Feature Request: Open On Focus

### ISSUE THREAD

**Issue by scs-ben** [sagalbot/vue-select#277]
Add an option for "open on focus."
We would like the select box to stay closed until the user hits enter or an arrow key.

**Comment by imrealashu** [comment]
I agree with @scs-ben but, I'd suggest little differently... The dropdown should except a boolean prop so that we can pass the prop value `true/false` to open/close the dropdown pragmatically.

**Comment by robinsonryan** [comment]
An additional option for this feature would be to have a prop value for the min number of characters required before the drop down opens.

**Comment by davidvleung** [comment]
Current work around would be 
    `this.$refs.select.open = true` 

where component defined as such 
    `<v-select ref="select" ... />`
