### ISSUE TITLE
How to center selected tag

### ISSUE THREAD

**Issue by nicolasvahidzein** [sagalbot/vue-select#279]
Hello,

how can i keep the selected tag centered? this is of course when it's not in "multiple" mode.

I want it centered nicely. Thank you. I'm able to center the place holder text but not the item contained in the dropdown.

**Comment by nicolasvahidzein** [comment]
Sagalbot, I really need your help on this.

**Comment by darkopetreski** [comment]
This can be solved by css. I can think of at least two ways:

Using flex:
'
.dropdown-toggle {
    display: flex;
    align-items: center;
    justify-content: space-between;
}
input.form-control {
    position: absolute;
}
`

Using absolute position, but this requires fixed width of the tag:
`
.selected-tag {
    position: absolute;
    left: 0;
    right: 0;
    margin-left: auto;
    margin-right: auto;
    width: 200px;
    text-align: center;
}
`
You may need to fine tune it. Please note that I haven't tested in various browsers.

**Comment by darkopetreski** [comment]
If you need to center the items in the drodown menu, even simpler

`
.v-select>.dropdown-menu {
   text-align: center;
}
`

**Comment by nicolasvahidzein** [comment]
Thank you @darkopetreski. We are close except that in the code i have there is no form control tag, i ended up changing this one but it collapses the box. :(

.v-select input[type=search],
.v-select input[type=search]:focus

**Comment by nicolasvahidzein** [comment]
Also its not centering the tag, it does not work.

**Comment by darkopetreski** [comment]
Here is a live preview of the absolute version (I live the flex version better, because of the auto width, but will do it when I have more time)
http://output.jsbin.com/zejonoroje

**Comment by nicolasvahidzein** [comment]
You sir are a genius, i will play around with it. Please tell me you are available to freelance? Can we chat on skype? nzein19 is my handle brother.

**Comment by nicolasvahidzein** [comment]
still no good, let me know if you are free to chat. It's messing up other parts now.
