### ISSUE TITLE
How to clean selected-tag

### ISSUE THREAD

**Issue by iulian34** [sagalbot/vue-select#304]
Hello, 
Is possible to clean input selected-tag after form submit?

**Comment by adarshsosale** [comment]
I had a very similar issue at hand. I simply hacked around it by using the :on-change function to retrieve the value into my function and resetting it there using :value.sync.

**Comment by michaelsogos** [comment]
I tried using :value.sync and also changing the parent data from :on-change event.

Data will be reactive as expected but the changes do not propagate to v-select.
What's is wrong? I'm using VUE 2.4.4

**Comment by vrajau** [comment]
Same problem here (using Vue 2.4.4), but it is kind of weird. I have a form using multiple vue-select, which are contained in a modal.
When you click on the button to open the modal, it is supposed to reset the form by setting vue-select default value to "null".

If I leave the modal, ad click on the button again, the selected tag is stil there, event if the default value for the vue-select is set to null (checked with console.log).

Even weirder, I tried to run some test, so I set the default value with a random object  {label: "test", value: "test"}, and added a button in my modal to reset the value to null, and it worked, so if the selected value come from the vue-select options you cannot set it to null, but if you set it by hand, you can.
