### ISSUE TITLE
Bulma is-fullwidth

### ISSUE THREAD

**Issue by Garito** [sagalbot/vue-select#322]
Hi!
How can I make the select full width with its container?
I'm usign bulma which will be using .is-fullwidth but doesn't work as class

**Comment by WebSpanner** [comment]
The following three selectors need to be styles with CSS to make the v-select component fullwidth:

        input,
       .dropdown,
       .dropdown-toggle {
            width: 100%;
        }

**Comment by Garito** [comment]
Sorry, I've solved myself by changing where to put the is-fullwith

**Comment by gerryhd** [comment]
Where exactly did you put the is-fullwidth? I ran into the same problem. WebSpanner's answer also works but I'd like to avoid modifying a default element's styles.

**Comment by Garito** [comment]
I'm sorry but I can't find where...
Will publish here if I find it
Meanwhile, try to put is-fullwidth in the parent... (trying to recall where I put it)

**Comment by buzdykg** [comment]
Lold
