### ISSUE TITLE
Control height do not match bootstrap input height

### ISSUE THREAD

**Issue by michaelsogos** [sagalbot/vue-select#325]
Dear @sagalbot ,

I notice that the control height, even if use `form-control` class, is taller than standard bootstrap input. About 2px.

**Comment by yurayakimenko** [comment]
So strange that maintainer had not answered this question. I got the same one.

**Comment by pranavkumar389** [comment]
@sagalbot My forms with vue-slect look ugly with other form-fields. It's not matching bootstrap form-control class. Any solution to this.

**Comment by dkabyshev** [comment]
@pranavkumar389 I've managed to change the height by setting it like so
`
.v-select .vs__dropdown-toggle {
  height: 40px;
}`

**Comment by pranavkumar389** [comment]
> @pranavkumar389 I've managed to change the height by setting it like so
> ` .v-select .vs__dropdown-toggle { height: 40px; }`

Yes, that will work for a single select. But selected options will overflow with `:mutlple="true`.
I have managed to remove some extra margin and padding from the box.
