### ISSUE TITLE
custom tags through raw html

### ISSUE THREAD

**Issue by okmkey45** [sagalbot/vue-select#399]
Hi. Nice component.

For my project, I had to add custom html inside the tags. More specific, for each tag, on the left side of the text, I needed a little square with a specific color.

Reading the docs, I could not find a solution for this. So, I solved my situation by copying the entire component, adding a new prop (optionLabelAsRawHtml) and using the v-html directive.

It could be useful for your package IF I didn´t miss anything reading the docs

**Comment by MarZab** [comment]
https://github.com/sagalbot/vue-select/pull/352
