### ISSUE TITLE
Autoselect option when Vuex store has value with Vue ~1.0

### ISSUE THREAD

**Issue by thorakmedichi** [sagalbot/vue-select#401]
This is virtually the same as this but with vue 1
https://github.com/sagalbot/vue-select/issues/133

I am trying to get the value that is stored in the vuex session state to auto select the country in the list if it is defined.

I have had SOME success with :value="selectedCountry" (where selectedCountry is the alpha2 iso stored in session / state) but it displays the alpha2 iso value in the UI rather than the 'label' in the array. I have had no success with v-model

here is what I have:
```
<v-select
    :value="selectedCountry"
    :on-change="updateCountry"
    :options="countryOptions">
</v-select>
```

where countryOptions = [{value: AU, label: Australia}, {...}]

I want countryOptions value AU selected but label Australia displayed. Currently it shows "AU" as label with :value="selectedCountry"

**Comment by bios-ben** [comment]
I'm unaware of how to handle this with v-model which maybe @sagalbot may want to comment on, but with :value you just need that to be the matching object from your options, i.e. "{value: AU, label: Australia}"
