### ISSUE TITLE
Mozilla Developer Firefox - Warning

### ISSUE THREAD

**Issue by evertramos** [sagalbot/vue-select#404]
I am having this warning after installed this component:

![image](https://user-images.githubusercontent.com/905951/34256004-5c69c722-e63a-11e7-94e4-8e618a8b71af.png)

**Comment by vitamink** [comment]
Is your web server configured to server `.js.map` files? Did you copy the `vue-select.js.map` file to the same dir as `vue-select.js`?

This warning just means that the browser can't download the map file, not a bug in vue-select. Take a look at this article for more info:
[https://www.html5rocks.com/en/tutorials/developertools/sourcemaps/](https://www.html5rocks.com/en/tutorials/developertools/sourcemaps/)

**Comment by evertramos** [comment]
I installed through:

`npm install vue-select`

I will take a look at the article.

**Comment by vitamink** [comment]
Most likely your web server is not configured to server `.js.map` files. You may need to update your server configuration. In any case, it's nothing to worry about.
