### ISSUE TITLE
Default local option when using remote data

### ISSUE THREAD

**Issue by vanpet** [sagalbot/vue-select#410]
Use case: 
1) by default, the dropdown options come from a local array when the user clicks on the search input at first
2) but when the user starts to type letters, the options are replaced by suggestions coming from the remote data
3) Repeat same process in case of "multiple" input for each tag (default local option on click, remote option on letters written).

How would you implement something like that?

**Comment by adrian999999** [comment]
You can use the normal vue select AJAX Remote Option Loading.
But instead assign` options: value` to local data and use onChange methods to reassign the options once ajax remote search is done.

```js
data() {
  return {
    options: null //assign do your local data on init
  }
},
methods: {
  getOptions(search, loading) {
    loading(true)
    this.$http.get('https://api.github.com/search/repositories', {
       q: search
    }).then(resp => {
       this.options = resp.data.items
       loading(false)
    })
  }
}

```
