### ISSUE TITLE
Selected values get reset right away

### ISSUE THREAD

**Issue by maxcook** [sagalbot/vue-select#455]
So myeditor is the Vue instance.  Inside i have a reusable input-container component that is meant for form inputs. The slot gets the form input and surrounds it with some stuff.
Inside I have a vue-select that has an issue. Whenever I select a value, the value gets displayed for a second or so and then disappears again. My guess is that there is an issue with associating the v-model so that the referenced model does not update. Any ideas?
Ah and 'data' is on 'myeditor'.

`<myeditor class="eventEditor" inline-template>  
    <input-container label="{{'Description'}}" :errors="editor.errors">  
        <template slot="input" slot-scope="slotProps">  
             <v-select ref='locationsSelect' multiple :filterable="false" :options="locationOptions"
                                      v-model="data.locations" @search="onLocationSearch">
        </template>  
    </input-container>  
</myeditor>`

**Comment by maxcook** [comment]
So with the vue dev tools I see that whenever i click/select an element in the list, then there are instantly   two events of type input emitted by v-select. The first one contains as payload the selected element while the second one ist just empty.

**Comment by 404dragons** [comment]
I have a similar issue. If there are two v-select components displayed, changing the "first" one gets reset and populated with data from the second. Even though they are bound to different models and options.

**Comment by mikebronner** [comment]
I'm having the same problem. Has anyone found a work-around for this yet?

**Comment by GustavoEX** [comment]
I'm having a similar issue. I have an variable in the vuex store that is used for the v-model property, whenever it gets mutated the chip on v-select disapears but the object is still in the value property. Can someone help me?
