### ISSUE TITLE
Taggable doesn't work on tab

### ISSUE THREAD

**Issue by redijedi** [sagalbot/vue-select#466]
I expect that when I enter a new entry and then tab away, that it will leave the new entry. However, the entry disappears when I tab away.

**Comment by mailnike** [comment]
It would be awesome if you add some kind of 'tab' prop.

**Comment by Yamaha32088** [comment]
It appears that this already exists. You just need to add the property "select-on-tab".

**Comment by Yamaha32088** [comment]
fixed with #554 and #555
