### ISSUE TITLE
On smaller devices, the single dropdown goes in two lines

### ISSUE THREAD

**Issue by darkopetreski** [sagalbot/vue-select#480]
If the width of the select is smaller, and the select is single, not searcable, the select should not increase in height, as in the screenshot. 

![screenshot-www squeaker local 2018 03 09 15-01-04](https://user-images.githubusercontent.com/4987585/37211023-e2b0a28a-23aa-11e8-970f-47d58e346fef.png)

**Comment by fractalocity** [comment]
duplicate of #430 #460 
the bug still exists

**Comment by darkopetreski** [comment]
Yes, duplicate.
