### ISSUE TITLE
How does one get the value of a selected option to submit via a normal form post?

### ISSUE THREAD

**Issue by Jaace** [sagalbot/vue-select#495]
I've tried using the v-model to populate a hidden input but all I get for that value is "[object object]". Am I missing something obvious here? This isn't documented from what I can tell.

**Comment by Jaace** [comment]
I figured this out (sort of) for anyone else having this problem. First of all, I needed to set the Vue.data option for selected to an object. If it's empty, it was showing up as `{}` so I instead set it to:
```
data: {
      selected: { label: 'Select a An Item', id: '' },
    },
``` 

Then, in a hidden input, outside of where I'm rendering, I include a hidden input alongside the component as such (left out the unimportant bits, focusing on this solution itself):
```
<v-select v-model="selected">
<input type="hidden" name="selectedItem" v-model="selected.id">
```

**Comment by kossa** [comment]
I had the same issue and It's very easy to add name as props then put 2 a hidden input!!!!!

**Comment by pcm0nk** [comment]
Hi, sorry to leaving a comment on this , but im trying to put the selected value in a hidden input box but i cant retreive the value, what am i missing ? 
`  <input type="hidden" name="selectedItem" v-model="selected">`
`<v-select v-tooltip.right="msg"  taggable max-height="100px" ref="jobbox" push-tags v-model="selected" dir="rtl" label="alljobstitle" name="selected"  :options="alljobsnew" ></v-select> `
im stuck!! thanks for any help

**Comment by patmull** [comment]
> I figured this out (sort of) for anyone else having this problem. First of all, I needed to set the Vue.data option for selected to an object. If it's empty, it was showing up as `{}` so I instead set it to:
> 
> ```
> data: {
>       selected: { label: 'Select a An Item', id: '' },
>     },
> ```
> 
> Then, in a hidden input, outside of where I'm rendering, I include a hidden input alongside the component as such (left out the unimportant bits, focusing on this solution itself):
> 
> ```
> <v-select v-model="selected">
> <input type="hidden" name="selectedItem" v-model="selected.id">
> ```

I don't know what is your whole implementation, but I would say it should be rather:
v-model="selected**.id**
```
<v-select v-model="selected.id">
<input type="hidden" name="selectedItem" v-model="selected.id">
```
