### ISSUE TITLE
How to fix warnings due to deprecated "scope" ?

### ISSUE THREAD

**Issue by devondahon** [sagalbot/vue-select#498]
I get the following warning due to `<template slot="option" slot-scope="option">` and `<template slot="selected-option" scope="option">`.

How should I fix it ?

> WARNING in ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-30a11342","hasScoped":true,"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./resources/assets/js/components/shared/transaction-add.vue
> (Emitted value instead of an instance of Error) the "scope" attribute for scoped slots have been deprecated and replaced by "slot-scope" since 2.5. The new "slot-scope" attribute can also be used on plain elements in addition to <template> to denote scoped slots.
>  @ ./resources/assets/js/components/shared/transaction-add.vue 10:23-276
>  @ ./resources/assets/js/app.js
>  @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

**Comment by kossa** [comment]
I had the same error but seems like `scope` is deprecated instead use `slot-scope`, also the example of Ajax : https://codepen.io/sagalbot/pen/POMeOX should be changed

So use :  `<template slot="selected-option" slot-scope="option">`

**Comment by kossa** [comment]
More info here : https://vuejs.org/v2/guide/components-slots.html#Scoped-Slots
