### ISSUE TITLE
clear selection icon not align

### ISSUE THREAD

**Issue by GitzJoey** [sagalbot/vue-select#515]
Hi, im having OCD problem
the clear selection icon not align with the drop down icon

how to fix this? thanks

https://imgur.com/a/IrrwN

**Comment by andywarren86** [comment]
I had it centered then it was moved in #416 
Have a look at the code change and you will see which CSS rule you need to modify

**Comment by GitzJoey** [comment]
hmm, i'm still puzzled on how to override it, since its inside the vue compenent style, and i dont want to change anything original in component. i see there's style attribute with empty value, is there any way to add custom style in it? thanks

**Comment by BasConijn** [comment]
Changing it back to 7px makes it align a lot better.

**Comment by GitzJoey** [comment]
understand that i need to change the bottom from 9 to 7 again, but i want to do it via injecting the css into the style tag, is it possibile?

**Comment by BasConijn** [comment]
I just added the following code to my .css
`.v-select .dropdown-toggle .clear {
	bottom: 6px !important;
}`
