### ISSUE TITLE
OnSearch not called when using Google Keyboard

### ISSUE THREAD

**Issue by BasConijn** [sagalbot/vue-select#516]
Load the ajax example on an android phone (https://codepen.io/sagalbot/full/POMeOX/).
Select the field and start typing something ("vue" for example).
No loading indicator is shown and no results are loaded.
Is seems that the onSearch is not called.

The normal selects (i.e with preloaded values) do work correctly.

Tested with Google Chrome on 66.0.3359.106 on android 8.0.0 and android 6.0.1
Weirdly enough it does work with the swiftkey keyboard.

**Comment by tomgillespy** [comment]
If I do remote debugging from a pc and use the PC's keyboard on the android device through the inspector it works too. It looks like the search watcher in mixins/ajax.js isn't calling for some reason...

**Comment by tomgillespy** [comment]
Turns out this is down to android not using input events properly. I'll submit a PR shortly for a fix using the keyup event.

**Comment by mrdigitalau** [comment]
If you hit the space bar it also fires the input event..

**Comment by Platon79** [comment]
As I can see changes from @tomgillespy works good. But it is still not in code. Can anybody approve and add it to final version or create another decision for this problem? So library will work great.
