### ISSUE TITLE
Dialog box not coming on selecting a option from dropdown

### ISSUE THREAD

**Issue by easverasuthan** [sagalbot/vue-select#521]
I'm trying to trigger a dialog box on selecting a option from dropdown. But it is'nt working.

**Comment by abdullah-abunada** [comment]
I found the problem, the extend bootstrap css overwrite the v-select style :(

**Comment by easverasuthan** [comment]
But i haven't used bootstrap anywhere

**Comment by abdullah-abunada** [comment]
you can define onSelect method and do any logic inside it
