### ISSUE TITLE
Input event emits as if it were onchange

### ISSUE THREAD

**Issue by TaylorDale** [sagalbot/vue-select#526]
Can't seem to re-open #504 - Close if inappropriate, but this behaviour is inconsistent with all other inputs - As mentioned in #504 this change would not break synchronisation. 

You can see this difference by performing a simple test:
```
computed: {
        Ouput: {
            get() {
                console.log("input GET");
                return "1";
            },
            set(v) {
                console.log("input SET");
            }
        },
        Ouput_Select: {
            get() {
                console.log("select GET");
                return "1";
            },
            set(v) {
                console.log("select SET");
            }
        }
    }
```

With an DOM setup like
```
<v-select :options = "['1','2','3','4']" v-model = "Output_Select" />
<input type = "text" v-model = "Output" />
```

When this DOM is rendered the first time you will get in the console:
> input GET
> select SET

Hope this is enough to showcase the inconsistency - and also prove that it won't desync the state!

**Comment by sylfel** [comment]
I have a similar case where nested select can't be initialize because first select reset next one !
