### ISSUE TITLE
TypeError: Cannot read property 'value' of null

### ISSUE THREAD

**Issue by dafinest** [sagalbot/vue-select#530]
so lam getting the error as shown on the picture below when running my chatbot on localhost

![image](https://user-images.githubusercontent.com/23218848/39555825-df1a0264-4e30-11e8-87e3-14ad400679a4.png)

this is the portion which has the error in vue.esm.js

function logError (err, vm, info) {
  if (process.env.NODE_ENV !== 'production') {
    warn(("Error in " + info + ": \"" + (err.toString()) + "\""), vm);
  }
  /* istanbul ignore else */
  if ((inBrowser || inWeex) && typeof console !== 'undefined') {
    console.error(err);
  } else {
    throw err
  }
}

**Comment by mrsweaters** [comment]
I'm also experiencing the same issue.
