### ISSUE TITLE
Ignoring diacritics

### ISSUE THREAD

**Issue by patie** [sagalbot/vue-select#534]
Hi! Select2 defaultly ignore diacritics, but vue-select lib not, any solution please?

**Comment by kizivat** [comment]
Does this being closed mean diacritics agnostic filtering is not considered for implementation?

**Comment by tberne** [comment]
@sagalbot,
It would be nice to have a feedback on why was this issue closed.
It is not considered a problem? 
There's already a way of doing that?

**Comment by tberne** [comment]
FYI: I've used in the `filterBy` prop a function that performs the filter by removing the accents.
The function I've implemented was based on [this one](https://github.com/shentao/vue-multiselect/issues/281#issuecomment-597718858).
