### ISSUE TITLE
@change not working

### ISSUE THREAD

**Issue by WebKieth** [sagalbot/vue-select#545]
"vue": "^2.5.16",
"vue-select": "^2.4.0",

```
<script lang='coffee'>
	Vue = require 'vue/dist/vue.js'
	setParams = Vue.component 'set-params',
		props: 
			params:
				type: Array
				required: true

		methods:
			getOptions: (srv) ->
				console.log('WTF')
				@$emit('get-option', srv)
	module.exports = setParams
</script>
<template>
	<div class='accordion__step step v-step'>
		<div class='step__selects'>
			<div class='v-step__select' v-for='select in params'>
				<v-select v-on:change='getOptions(select.get)' class='v-step__v-select' v-if='select.options.length === 0' label='text' :placeholder='select.placeholder' :disabled='true'></v-select>
				<v-select v-on:change='getOptions(select.get)' class='v-step__v-select' v-else label='text' :placeholder='select.placeholder' :options='select.options'></v-select>
			</div>
		</div>
	</div>
</template>
```
console log and emitter not worked. Also I tried v-on:change @select, @selected.
event starts working after @input. I didnt find any info about event API, only prop function "onChange".
pls, add some info about event API

**Comment by serjoscha87** [comment]
got the same issue; 

the problem with @input is that its triggered on page load and not only when the value is changed. In my case this causes an unnecessary rest api request. So I am also looking for an working change event to hook into

**Comment by cacciatc** [comment]
@WebKieth does using ```:on-change="getOptions"``` work for you?

**Comment by WebKieth** [comment]
@cacciatc I tried to use :on-change instead @input and when i render selects and try to set option, browser tab stopped responsing, it seems like infinite iteration, but i cant test - context menu and hotkey for opening console not responsing too. 
So i stay to use @input =)

**Comment by kateno** [comment]
same issue here, @input does the job for me and saved me, thanks!

**Comment by TaylorDale** [comment]
This behaviour is inconsistent with pretty much everything else unfortunately... see #526 #504 as well

**Comment by Pirakavi-Santhiran** [comment]
@input, @change, v-on: change are not working but v-on: click is working when I use datetimepicker
