### ISSUE TITLE
how to reset mutableValue to null after options removing?

### ISSUE THREAD

**Issue by WebKieth** [sagalbot/vue-select#546]
Hello.
Situation:
I have got a big step-to-step component, which last step is a group of v-selects, which rendered by v-for directive:
```html
<div class='accordion__content'>
	<set-access v-if='step.action === "set-access"' :service-data='step.groups' @set='setAccessService' @next='goNext(idx)'></set-access>
	<get-access v-if='step.action === "get-access"' :access="step.access" @add-access='addAccess(step.service)' @next='goNext(idx)'></get-access>
        #component with v-selects inside
	<set-params @get-option='getOptionParams' v-if='step.action === "set-params"' :params="step.params"></set-params>
</div>
```
choosing of first select do a request for other select options and if select have no options, i want to disable it
```html
<div class='step__selects'>
	<div class='v-step__select' v-for='select in params'>
		<v-select v-on:input='getOptions(select.get)' class='v-step__v-select' v-if='select.options.length === 0' label='text' :placeholder='select.placeholder' :disabled='true'></v-select>
		<v-select v-on:input='getOptions(select.get)' class='v-step__v-select' v-else label='text' :placeholder='select.placeholder' :options='select.options'></v-select>
	</div>
</div>
```
On a first step opening disabled option and placeholder works fine, but if i want to return to previous steps and reset my set-params data (so options from some selects removed from data) mutableValue didnt reset to null and disabled selects rendered with last setted option instead placeholder.

**Comment by gemilaguinaldo** [comment]
in my case, i directly edited the mutableValue (via ref) and set it to null. hopefully they add a function that clears the mutableValue whenever the v-model is set to null..

**Comment by ijy5154** [comment]
https://vue-select.org/api/props.html#resetonoptionschange

When false, updating the options will not reset the select value (Default : false)
