### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0, need help with javascript code modification

### ISSUE THREAD

**Issue by wisamx** [sagalbot/vue-select#550]
I have copied this code form the example

```
Vue.component('v-select', vSelect);

new Vue({
    el: '#create-product-app',
    data: {
            options: []
        },
        methods: {
            maybeLoad() {
                return this.options.length <= 0 ? this.load() : null
            },
            load() {
                this.$refs.select.toggleLoading(true)
                fetch('https://reqres.in/api/users')
                    .then(res => res.json())
                    .then(json => {
                        this.options = json.data
                        this.$refs.select.toggleLoading(false)
                    })
                    .catch(err => console.warn(err))
            }
        }
    })
```

and the webpage contain this element

```
        <v-select
                ref="select"
                label="title"
                :options="options"
                @search:focus="maybeLoad"
        ></v-select>
```
and it worked well.

I have these json data on the local url:
http://localhost/SyriaShop/public/admin/1/vocabulary?api=true

`[{"id":2,"title":"Categories","description":null,"metadata":null,"global":1,"store_id":1},{"id":3,"title":"Manufactures","description":null,"metadata":null,"global":null,"store_id":1},{"id":4,"title":"Colors","description":null,"metadata":null,"global":null,"store_id":1},{"id":5,"title":"Sizes","description":null,"metadata":null,"global":null,"store_id":1},{"id":6,"title":"CPU Names","description":null,"metadata":null,"global":null,"store_id":2},{"id":7,"title":"ss","description":null,"metadata":null,"global":null,"store_id":1},{"id":8,"title":"df","description":null,"metadata":null,"global":null,"store_id":1},{"id":9,"title":"sssssss","description":null,"metadata":null,"global":null,"store_id":1}]`

I tried to modify the code to work with such data. but I just failed and failed.
and the console says: 'SyntaxError: Unexpected token < in JSON at position 0'

I hope somebody could help me modify the code.

**Comment by BogdanStanciu** [comment]
You have check if the ajax request: `fetch('https://reqres.in/api/users').then(res => res.json())` have the permission or you have set the `X-CSRF-TOKEN` ? It's seems that redirect in the middleware auth.
