### ISSUE TITLE
How to select an option in automated tests?

### ISSUE THREAD

**Issue by vitobotta** [sagalbot/vue-select#567]
Hi, and thanks a lot for this component, very useful. I am looking for how to select an option from a vue-select from an automated test. jQuery/Select2 uses a normal select behind the scenes so I could just select an option from that one in my tests, and that works. But it seems like vue-select doesn't use a normal select at all, is this correct or am I missing something? In any case how can I trigger the selection of an option?

Thanks!

**Comment by viniciusalonso** [comment]
Nice! I think that I'll take this same way. Early, I was trying to understand how it component works using the google chrome devtools. But I need to save time at work. So, I will turn in this direction. Thanks @vitobotta

**Comment by saltlakeryan** [comment]
I've used a javascript function for this:

```javascript
function setVueSelectOption(id, val) {
                        //get the vue component for vue-select
                        var v = document.getElementById(id).parentElement.parentElement.__vue__;
                        
                        //call the select function in Select.vue (under methods)
                        v.select(v.mutableOptions.filter( op => 
                            {
                                if (op.name != null) {
                                    return op.name == val;
                                } else {
                                    return op == val;
                                }
                            })[0]);
			    v.open=false;
                    }
```

Where I've set the id of the inner select element by passing the input-id property.

**Comment by speker2010** [comment]
vue-select-utils
```
const input = this.wrapper.find('#select-id'); // select-id is `inputid` value
await input.trigger('click');
input.setValue(value) // value is text from target 'option'
await input.trigger('keydown.enter');
```

selenium-webdriver
```
const select = driver.findElement({css: '#select-id'}); 
await select.click();
await select.sendKeys(value, Key.ENTER);
```
