### ISSUE TITLE
select trigger multiple times

### ISSUE THREAD

**Issue by rockyshukla** [sagalbot/vue-select#568]
hello guys why my select trigger multiple time after press final submit in bootstrap modal
here is issue 

           <button type="button" style="width: 110px;" class="btn btn-sm btn-primary" variant="secondary" @click="largeModal = true">Add </button>

             <b-modal title="Shops Establishment" size="lg" v-model="largeModal" @ok="largeModal = false">
                   <div class="row">
                        <div class="col-sm-12">
                           <div v-if="hasErrors.message" class="alert alert-success" >
                                <center> <strong></strong>{{errorMessage.message}}</center>
                           </div>
                      </div>
                </div>
              <v-select v-model="con" :options="conopt" label="country_name" @input="state1"></v-select>
              <v-select v-model="state"  label="state_name" :options="stateopt" @input="city1"></v-select>  
              <button type="submit" class="btn btn-primary" @click.prevent="Successsub()"><i class="fa fa-dot-circle-o"> </i> &nbsp;Save</button>
         </b-modal>
            data{
               return{
                             con:null,
                            state:null,
                            conopt:[],
                           stateopt:[],
                      }
              }
          method:{

              contr1(){
               console.log("contr trigger")
                 var _this=this
                   this.$http.get('/api/countries')
                        .then(function(response){
                        console.log(response)         
                            _this.conopt=  response.data;
                   }).catch(function(error){
                         console.log(error.response)
                   })
                },
          state1(conopt){
               console.log("state trigger")
              var _this=this
                  var id=conopt.id
                 this.$http.get('/api/states?filter[where][country_id]='+id)
                    .then(function(response){
                       
           
                          _this.stateopt=  response.data;
                      }).catch(function(error){
                  console.log(error.response)
              })
     
           },
            Successsub(){
               this.$http.post('/api/shopestablishments',shop)
             .then(function(response){
            _this.hasErrors.message=true;
             _this.errorMessage.message= 'Successfully Shop Added';
             _this.reset();
             _this.conopt=[]
            _this.con = null;
          
               }).catch(function(error){
                        console.log(error.response)
                })
                  }
         }
              reset(){
               var _this=this;
              _this.shop.name ='';
             _this.con=null,
              _this.state = null;
           },
          }
here is my console log image link  https://imgur.com/a/dS6NvLn

**Comment by Jerome1337** [comment]
I'm facing the same problem, the select has been re-opened when I select a value.

Did you find some clues @rockyshukla
