### ISSUE TITLE
@input is called on component load?

### ISSUE THREAD

**Issue by gecevicius** [sagalbot/vue-select#573]
Is @input event supposed to be called on page load? If so, is it possible to prevent that?
My code : 
`<v-select label="manufacturer" placeholder="Search for equipment..." :value="this.$store.state.selectedEquipment" :options="this.$store.state.equipment" @input="setSelectedEquipment($event)"></v-select>`

`setSelectedEquipment(e){
				this.$store.dispatch('selectEquipment',e)
				this.$router.push('equipment')
			}`

**Comment by amilabell** [comment]
Any updates on that? I am having the same issue

**Comment by cioraneanu** [comment]
I am trying to create my own form watching mechanism to see if the user has changed any of the fields. 

It would be awesome if there was a prop to set if the initial value should emit the @input event.

**Comment by antonioribeiro** [comment]
Huge problem with this here, because it's setting a null when loading.

**Comment by dbaehr15** [comment]
hoping this gets resolved
