### ISSUE TITLE
On mobile, options are not filtered on input, only when keyboard closed

### ISSUE THREAD

**Issue by andreiciceu** [sagalbot/vue-select#580]
Hello,

Firstly, great plugin, congrats :)
I've encountered a problem on Android mobile device in Chrome:
options are not filtered on key input, only after closing the keyboard (clicking outside of the select).
Probably happens because the value of an input is only changed on mobile when the keyboard has been closed.
A solution could be to watch the @keyup event and update value accordingly. I'd try to fix it via a fork & PR, but unfortunately I haven't been able to build it, as I get the error mentioned in issue #306 

Many thanks

**Comment by boldenkintaro** [comment]
I've encountered the same problem.

**Comment by tetianakh** [comment]
I'm facing the same issue. Is there any workaround?
