### ISSUE TITLE
Assigning Id to Data but Displaying Name

### ISSUE THREAD

**Issue by Mornney** [sagalbot/vue-select#582]
Hi, 
Im not sure if this is the right place, please point me to a better place to ask this. 

I am trying to complete a form in a .net core project (MPA), on a Vue form I have some drop downs where I would like users to be able to select from a list.

I believe I have implemented vue-select correctly, though I am having issues binding the id to the data model instead of the name, in normal vue this was doing the correct job:

```
<select class="form-control" id="corporation" v-model="venue.venueCorporationId">
         <option v-for="corporation in venueReferences.corporations" v-bind:value="corporation.id">
                   {{ corporation.name }}
        </option>
</select>
```

This is what I am trying to do with vue-select:

```
<v-select taggable v-model="venue.venueCorporationId" label="name" :options="venueReferences.corporations">
        <template slot="option" slot-scope="option" v-bind:value="option.id">
                    {{ option.name }}
        </template>
</v-select>
```

The object venue has multiple values to it (name, address, phoneNumber, corporationId.

venueReferences.Corporations is a list of objects as followed
[
{ id: 1, name: corporationOne }
{ id: 2, name: corporationTwo }
]

I want to display the names to the user (which is currently happening)
I want the user to be able to search by typing into the select input (which is currently possible)
I want the user to be able to enter a new corporation (which is happening with the taggable)
I want the id to be bound to the venue object {{ venue.corporationId }} (This is not working like the standard select)

Can anyone point me into what I am doing wrong please?

Thank you in advance

**Comment by kotarCreative** [comment]
The template is not currently doing anything. If you want to bind the id specifically just create a computed value to bind the v-model to and define an explicit setter and getter method. That will allow you to extract the id from the object before setting it on `venue.venueCorporationId`. 

It could look something like this.
```html
<template>
    <v-select taggable
              v-model="venueId"
              label="name"
              :options="venueReferences.corporations">
    </v-select>
</template>
<script>
    export default {
        computed: {
            venueId: {
                get() {
                    return this.venue.venueCorporationId;
                },
                set(venue) {
                    this.venue.venueCorporationId = venue ? venue.id : null;
                }
            }
        }
    }
</script>
```
