### ISSUE TITLE
clearSearchOnSelect and search input "placeholder"

### ISSUE THREAD

**Issue by NikolaySav** [sagalbot/vue-select#592]
Greetings!

Having trouble with configuring component for my needs. 
The expected behaviour: search value stays after blur and user can type further. 
:clearSearchOnSelect="false" provides some kind of expected behaviour but search value duplicates (image provided below).

How can i get rid of this duplicated value?

![image](https://user-images.githubusercontent.com/13363510/42809166-9dad8df0-89bd-11e8-95e3-94299b70e0bb.png)

Thanks in advance.

**Comment by nickescobedo** [comment]
@NikolaySav can you post a codepen or jsfiddle demonstrating this issue please?
