### ISSUE TITLE
Searchable clear button won't disappear with semantic UI

### ISSUE THREAD

**Issue by Amaurgit** [sagalbot/vue-select#597]
Hi there ! 
First, thanks for this amazing work :) 

Do you have any idea why my dropdown keeps this clear button while :searchable is set to false ?
 I suspect semantic to add some CSS but I can't get rid of it (I'm in scoped CSS in Vue).

 Thank you :)
![capture](https://user-images.githubusercontent.com/4455870/42931989-6cf9b442-8b41-11e8-973a-bb51e27cfa72.PNG)

**Comment by jackleblack-kpt** [comment]
Hey, 

You must hide the button in css : 

```
.select-no-cleareable .clear {
  display: none;
}
```

**Comment by Amaurgit** [comment]
@jackleblack-kpt Thank you :)
