### ISSUE TITLE
Delete key clears vue-select even if clearable is false

### ISSUE THREAD

**Issue by GiuMagnani** [sagalbot/vue-select#634]
If I put the focus on the select with <kbd>tab</kbd> key and press <kbd>backspace</kbd>, the vue-select gets emptied and returns null. This also happens if I pass the new `clearable` prop as false.

I need that the vue-select never returns a `null` value.

Is there any way to fix this behaviour?

**Comment by GiuMagnani** [comment]
It also happens if I click the `vue-select` and press the <kbd>backspace</kbd> or <kbd>supr</kbd>.

**Comment by skayablars** [comment]
any update on this?

**Comment by kepeder** [comment]
If anyone having problems with this; a workaround:

    watch: {
      country: function (current, prev) {
        if (current === null && prev !== null) {
          this.country = Object.assign({}, prev)
        }
      }
    }

**Comment by GiuMagnani** [comment]
I have 50-100 select components in my app, so that solution is not really convenient. At the end, I changed my components to the Element select: https://element.eleme.io/#/en-US/component/select

**Comment by hrobertson** [comment]
I don't think this change was fully thought through. It can't be considered just a bug fix - it changes the functional behaviour of vue-select.

Prior to this change, the only effect of the `clearable` prop was to specify whether the clear button should be displayed as per the `showClearButton` method. - i.e. it was a purely aesthetic option which did not effect the functional behaviour.

After #723, the selection cannot be cleared by pressing <kbd>backspace</kbd> or <kbd>delete</kbd>. When multiple=true, selections can still be deselected by clicking the X on the option but not by pressing <kbd>backspace</kbd> or <kbd>delete</kbd>. This seems like incorrect behaviour to me.

I suggest that the previous behaviour be restored and a new prop `allowNull` should be added which when false prevents the value from being unset, and for multiple=true ensure that at least one option is selected.

**Comment by sblawrie** [comment]
Yes, I agree with @hrobertson. This seems like a bug. When I delete a selection using backspace or delete, it clears the selection from the dropdown but **it does not remove it from the model**. If I delete the selection by clicking the X, it works properly.

**Comment by strstr1** [comment]
I have the same issue as @hrobertson 

Did someone found a solution to remove the values from the v-model by backspace / delete key?

Thank you!
