### ISSUE TITLE
Unable to multi-select and use taggable with bootstrap

### ISSUE THREAD

**Issue by karthikbadarinath** [sagalbot/vue-select#641]
Hello

We are using `v-select` `taggable` with `multiple` functionality from `2.4.0` and does not seems to be working in `2.5.0` update.

**Here is the issue:**

1. When you click on select button (with multiple and taggable true) the drop-down opens for first one just fine, we then select one and try to select another one (by just clicking on the select button and expect to see a drop-down/area to type). Here the select button will become unclickable / will not allow us to add any new items (but it becomes **selectable only** when we select down caret symbol)
2. Another observation that we did here is, this happened only when we use bootstrap, which adds hidden class to the input field making it unselectable.

**Here is the example that we are going through**
http://jsbin.com/ledenanefu/edit?html,js,console,output

**Feel free to**
1. Change the version back to 2.4.0 from 2.5.0, which works fine
2. Remove bootstrap and retain 2.5.0 (as per my second point)

**More info on versions we are using**

```
vue: 2.5.17
vue-select: 2.5.0
bootstrap: 3.1.3
```

**Comment by Prasad2205** [comment]
We are facing the same issue even with the vue-select: 2.4.0. Unable to generate the multiple tags after typing and selecting the first tag. The input field (select box ) get unclickable so not able to type the next tag.
