### ISSUE TITLE
is there a "Selecting" event ?

### ISSUE THREAD

**Issue by moosapour-arash** [sagalbot/vue-select#656]
hello, In select2 there is a 'select2: selecting' event that

> Triggered before a result is selected. This event can be prevented.

this is useful to pop a confirm alert before actually change the selected option.
is there a way to achieve same with vue-select?

**Comment by JGKL** [comment]
I believe this is not supported right now.

**Comment by moosapour-arash** [comment]
is there any workaround for this?

**Comment by Yiidiir** [comment]
You could watch or track the value of `v-model`

**Comment by lovrozitnik** [comment]
See documentation for @input.
[https://vue-select.org/api/events.html#input](https://vue-select.org/api/events.html#input)

`<v-select @input='yourOnSelectedMethod($event)></v-select>`
