### ISSUE TITLE
installation and use problems

### ISSUE THREAD

**Issue by jallowmamadou** [sagalbot/vue-select#66]
i install vue-select via npm and then i have a problem with my resource stop working. i am using laravel  elixer. can you please the installation process for someone using laravel with vue?

**Comment by bladesling** [comment]
I had this same issue. For me it was a dependency issue. It's included in the vue-select's package.json but npm never downloads it.

My solution was to include the the missing package in my package.json.

"babel-preset-stage-2": "^6.5.0"

Seems pretty odd but it worked for me.

**Comment by jallowmamadou** [comment]
thanks for responding but i already have barble ^6.6.0. i ended not implementing plugin. it seem to be a good plugin but it did not work for me.
