### ISSUE TITLE
multiple options (objects) does not disable selected options properly

### ISSUE THREAD

**Issue by telcy** [sagalbot/vue-select#671]
When I am using multiple options (objects) it does not disable the selected options properly. It is possible to select the same option multiple times.

I have created a demo on codepen: https://codepen.io/telcy/pen/KGMqgm

**Comment by Vireshhemraj** [comment]
I also have the same problem.Have you found  a workaround?

**Comment by travis18** [comment]
I tried to use version 2.4.1 and this issue was gone.

**Comment by travis18** [comment]
> dude what are talking about? https://codepen.io/Vireshh/pen/GYWaPE
> still allowing duplicates... are you using multiple or single select?...You need to select eg foo then bar then you can select foo again ...which is a duplicate in your selection

try this one:
https://codepen.io/travis18/pen/zmZgpR

**Comment by Vireshhemraj** [comment]
Thank you @travis18. I got it to work.

**Comment by amstrad** [comment]
> > dude what are talking about? https://codepen.io/Vireshh/pen/GYWaPE
> > still allowing duplicates... are you using multiple or single select?...You need to select eg foo then bar then you can select foo again ...which is a duplicate in your selection
> 
> try this one:
> https://codepen.io/travis18/pen/zmZgpR

I can´t get this working in latest vue-select **2.5.1** (but your pen uses vue-select 2.4.0 and it works :/ ). I´m i missing something or is this bug related to 2.5?
https://codepen.io/amstrad/pen/pxppRK

![captura de pantalla 2018-10-16 a las 16 37 35](https://user-images.githubusercontent.com/772421/47024374-d3c90680-d161-11e8-9212-0eee6d1da90d.png)

**Comment by travis18** [comment]
> > > dude what are talking about? https://codepen.io/Vireshh/pen/GYWaPE
> > > still allowing duplicates... are you using multiple or single select?...You need to select eg foo then bar then you can select foo again ...which is a duplicate in your selection
> > 
> > 
> > try this one:
> > https://codepen.io/travis18/pen/zmZgpR
> 
> I can´t get this working in latest vue-select **2.5.1** (but your pen uses vue-select 2.4.0 and it works :/ ). I´m i missing something or is this bug related to 2.5?
> https://codepen.io/amstrad/pen/pxppRK
> 
> ![captura de pantalla 2018-10-16 a las 16 37 35](https://user-images.githubusercontent.com/772421/47024374-d3c90680-d161-11e8-9212-0eee6d1da90d.png)

I am not sure if it's a bug related to 2.5, but it didn't happen in 2.4.0. I can only use this version as workaround.

**Comment by Vireshhemraj** [comment]
https://github.com/sagalbot/vue-select/issues/630

its a bug  for 2.5 use 2.4.0

**Comment by totola-clx** [comment]
I just made a pull request to fix this issue.
Please, let me know if it needs some improvements.

**Comment by marbuser** [comment]
Is there any update on this? This is still broken in 2.5.1...

**Comment by vdjagilev** [comment]
@marbuser should bump this one https://github.com/sagalbot/vue-select/pull/693

**Comment by msherax** [comment]
i am also facing same issue. for now, i think i should switch to v2.4.0

**Comment by buttermilktoast** [comment]
hey there,  I too am also facing the same issue with the latest version.  v2.4.0 works, but with storing the actual objects in the model instead of the value
