### ISSUE TITLE
Component stuck after click "Sorry, there are no match options" option

### ISSUE THREAD

**Issue by italoSilveira** [sagalbot/vue-select#689]
Hey there,
I was playing with the component and saw this bug. When I click the "Sorry, there are no match options"option, the component hangs:
![vue-select-issue](https://user-images.githubusercontent.com/32437227/47299545-d2c82700-d5f0-11e8-9dc4-b0cab2c308dc.gif)

You can see the code here and try ourself: https://codepen.io/sagalbot/pen/XVoWxm

**Comment by haniefutama** [comment]
I have this issue as well. No console out put as well. Anybody has an idea?

**Comment by italoSilveira** [comment]
Meanwhile, someone has found a temporary solution https://github.com/sagalbot/vue-select/issues/648#issuecomment-424812677 :

```
<template slot="no-options">
        <div @mousedown.stop="">
          Begin typing to search (at least 3 letters)
        </div>
</template>
```
