### ISSUE TITLE
Adding Support for paginated AJAX API

### ISSUE THREAD

**Issue by andreabianchi** [sagalbot/vue-select#698]
I need to use the component with existing paginated API.

Like in your example [AJAX vue select](http://sagalbot.github.io/vue-select/docs/Advanced/Ajax.html) you call the API [api.github.com](https://api.github.com/search/repositories) that can return a multiple page of result.
In this api the presence of another page is comunicated with ""incomplete_results": true," in the response.
I don't find any built in mechanism to do that.
I expect that next page is requested and appended to the dropdown when the user arrived at the end of the scroll.

Thanks in advance.

**Comment by developius** [comment]
I've implemented pagination in my API and I plan to tackle this by returning 25 results by default and letting the user keep typing until they get a match. I don't really foresee this being a problem because it's pretty likely they'll get a match in the first 1-5 characters, which I think is acceptable. Your use case may differ though.

**Comment by andreabianchi** [comment]
Sometimes my users know only one subpart of the name that they try to find.
So, after writing the first word they usually continue visually searcing the preferred match inside the results that must be more than 25 records.

This scenario are very usefull when i don't show only one property of the results, but multiple columns with more property.

Example:
i search for "Pizza" and i try to select the cheapest.

**Comment by njc1431985** [comment]
@andreabianchi hey... is there an example codepen showing this? i.e. v-select with pagination as in this example [paginated](https://vue-select.org/guide/pagination.html) but where the data is not static, but is loaded dynamically using ajax calls to external api as explained in [ajax](https://vue-select.org/guide/ajax.html#loading-options-with-ajax).. I tried combining both using [code pen example](https://codepen.io/sagalbot/pen/POMeOX) but did not succeed. I am still new to Vue. So a example would really help understand working with v-select.

**Comment by garyapps** [comment]
It says the issue has been resolved but I can’t find an example of how to do this.

@njc1431985 and @andreabianchi , did either of you figure out how to get the data with Ajax and also have pagination?
