### ISSUE TITLE
Style background

### ISSUE THREAD

**Issue by jllagerberg** [sagalbot/vue-select#734]
Simple question. How do I change background colour from the default blue?

I can't find the class names to override in the css.

**Comment by KristapsK-globitex** [comment]
If you are referring to the mouse over color in the options dropdown:
.v-select .dropdown-menu>.highlight>a{
background: $yourBackgroundColor;
}

**Comment by jllagerberg** [comment]
> 
> 
> If you are referring to the mouse over color in the options dropdown:
> .v-select .dropdown-menu>.highlight>a{
> background: $yourBackgroundColor;
> }

Had to do an !important as well, but this worked. Thanks!
