### ISSUE TITLE
Prevent "Enter" key on mobile

### ISSUE THREAD

**Issue by Tusko** [sagalbot/vue-select#776]
Hi, thank you for a great component.
I have one question.

How to prevent "Enter" (or search icon on Android) key on the mobile phone?
I have AJAX select+search, and when I click enter/search button it chose the first suggestion from the dropdown.

How can I fix it?

**Comment by Tusko** [comment]
Hey, guys.
Any news?

**Comment by chiptus** [comment]
I would love to have a way to disable enter myself
