### ISSUE TITLE
Enter submits the form

### ISSUE THREAD

**Issue by udimitri** [sagalbot/vue-select#847]
**Describe the bug**
When enter is pressed, the form submits. This makes searchable tagging difficult. It looks like the problem is its prevented on `keyup` instead of `keydown`. I saw #249, I'm not sure if it was intentional in v3 or was just missed. 

**To Reproduce**
1. Go to [codepen](https://codepen.io/udimitri/pen/zXayaw)
2. Focus the select and click enter.

**Expected behavior**
Only the value should be selected, the form should not be submitted. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 73.0.3683.103

**Comment by rdarcy1** [comment]
For anyone needing a (hacky) workaround until #849 is merged, see a possible solution here: https://codepen.io/RobinKlever/pen/pXrRKP

I attached a submit event handler to the form, then on every event check to see if the event originated from within the vue select element.

**Comment by vitaliy-k** [comment]
To fix this error, simply add the following to parent `@keydown.enter.prevent.self=""`

**Comment by borekl** [comment]
@vitaliy-k Your solution will just prevent from submission with Enter, right?

**Comment by fadziljusri** [comment]
> To fix this error, just add `@keydown.enter.prevent.self=""` parent of `vue-select` component.
> 
> e.g. `<form @keydown.enter.prevent.self=""><v-select>`

This is good example, but if you want prevent submit ONLY on options when enter press  :- 

```html
<form @keydown.enter="onEnterKeyDown"><v-select>
``` 
and in methods:

```js
onEnterKeyDown(e) {
     if (e.target.className.includes("vs__search")) {
            e.preventDefault();
      }
}
```

**Comment by mihai-craita** [comment]
> @vitaliy-k Your solution will just prevent form submission with Enter, right?
the @keydown.enter.prevent.self="" can be on a parent wrapper like a div, so the form can still submit on enter.
