### ISSUE TITLE
Focusing v-select programmatically auto-selects a dropdown option

### ISSUE THREAD

**Issue by ThomasFindlay** [sagalbot/vue-select#883]
**Describe the bug**
V-select does not behave as expected when trying to focus it programmatically while it has a selected value. I have a usecase in which I need to focus v-select after a user presses enter on a different input field. I access the v-select search input ref and triggered 'focus()' on it. However, v-select automatically selects a dropdown option and triggers input event. I have created CodeSandbox with an example - https://codesandbox.io/s/vue-template-rq4qw.

**To Reproduce**
1. Select any option in the v-select
2. Type something in the input field
3. Press enter in the input field
4. V-select is being focused, but immediately is closed whilst selecting an option and triggering an input event.

**Expected behavior**
The v-select should be focused without automatically selecting any options whilst keeping dropdown open.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 70.0.3538.67

**Additional context**

**Comment by rstoye** [comment]
It seems the select is focused, before the enter-key has finished processing the event, thus triggering "enter" after the focus and selecting an option.

It works if you change
`@keypress.enter="keypress"`
to
`@keyup.enter="keypress"`

It's a workaround for sure, but maybe that's enough to satisfy your requirements.

**Comment by ThomasFindlay** [comment]
@rstoye Thank you, that works.
