### ISSUE TITLE
Dropdown not aligned correctly

### ISSUE THREAD

**Issue by Rav23** [sagalbot/vue-select#915]
Hi there,
First of all I'd like to congratulate you on this awesome component.

I'm quite unable to figure out why it wont work as expected when used in conjuction with bulma css. The dropdown seems skewed. I've tried disabling the bulmacss from my setup but I get the same result everytime.

<img width="1216" alt="Captura de ecrã 2019-07-28, às 2 16 35 PM" src="https://user-images.githubusercontent.com/2884479/62007240-0701e280-b143-11e9-9ba9-4ae8e91df32f.png">

**Comment by Rav23** [comment]
For anyone else who might have run into the same scenario, here's a fix:

`ul.vs__dropdown-menu {
    list-style: disc outside;
    margin-left: 0em;
    margin-top: 0em;
}`

Thank you once again for this awesome component.

**Comment by stran12** [comment]
@omdesignz saved me!
