### ISSUE TITLE
Vue-select doesn't reactive

### ISSUE THREAD

**Issue by bagaskarala** [sagalbot/vue-select#917]
**Describe the bug**
Vue-select is not reactive if we set the v-model. In other words, can't be selected programmatically.

**To Reproduce**
1. Just change your v-model of vue-select to other value
2. Then vue-select doesn't reactive follow the changes

**Expected behavior**
It should change reactive follow the v-model that we set.

**Screenshots**
<img width="647" alt="bug vue-select" src="https://user-images.githubusercontent.com/14112952/62115280-634f3880-b2e2-11e9-8fde-2e213bfc8568.png">
In the pic above, i use bootstrap-vue form-select on top and use vue-select on bottom. You can see if we change the roleId as seen in the vue-dev-tools, the vue-select doesnt change the selected value.

**Desktop (please complete the following information):**
 - OS: Windows 10 home
 - Browser Chrome 
 - Version 75.0.3770.142 (Official Build) (64-bit)

**Additional context**
it is very annoying that one of most popular select plugin on vue doesnt have reactivity. please fix that issue, thx.

**Comment by porcelanosa** [comment]
Can you provide code example?
I have [similar issue](https://github.com/sagalbot/vue-select/issues/912) but model is reactive

**Comment by doits** [comment]
See #914 where one of such cases is fixed. Maybe it fixes your problem, too?

**Comment by bagaskarala** [comment]
> See #914 where one of such cases is fixed. Maybe it fixes your problem, too?

Oohh i see, i'm using reduced primitive value to programmatically select. It should use one of the option.

Ok clear, solved thanks!

**Comment by Thainvn** [comment]
> > See #914 where one of such cases is fixed. Maybe it fixes your problem, too?
> 
> Oohh i see, i'm using reduced primitive value to programmatically select. It should use one of the option.
> 
> Ok clear, solved thanks!

Can you send me your code , I have same problem
