### ISSUE TITLE
Reduce, V-Model and Key not working with multiple instances of v-select

### ISSUE THREAD

**Issue by robertmarney** [sagalbot/vue-select#925]
**Describe the bug**
When multiple instances of vue-select are present with v-model data only the first instance selects the proper record.

**To Reproduce**

Component Template:

><template>
  <div
    class="control">
      <v-select
        label="name"
        :inputId="name"
        :options="users"
        :reduce="user => user.id"
        :key="user_id"
        @input="setUser(user_id)"
        v-model="user_id"
        class="control loading"
         >
      </v-select>
  </div>

</template>

![image](https://user-images.githubusercontent.com/48888686/62635734-79b64f00-b8f5-11e9-8520-a12e89404cbb.png)

Calling Multiple Times:

`<div class="column ">
            <b-field horizontal label="Team">
              <div class="columns" >
                <div class="column">
                  <b-field labelPosition="on-border" label="Manager" message="Required">
                    <user-select v-model="bid.manager_user_id" :user_id="bid.manager_user_id" :end_point="'users/'" :name="'manager'" />
                  </b-field>
                </div>
                <div class="column">
                  <b-field labelPosition="on-border" label="Primary Buyer">
                    <user-select v-model="bid.buyer_user_id" :user_id="bid.buyer_user_id" :end_point="'users/'" :name="'buyer'" />
                  </b-field>
                </div>
                <div class="column">
                  <b-field labelPosition="on-border" label="Primary Expeditor">
                    <user-select v-model="bid.expeditor_user_id" :user_id="bid.expeditor_user_id" end_point="users/" :name="'expeditor'"/>
                  </b-field>
                </div>
                <div class="column">
                  <b-field labelPosition="on-border" label="Responsible Engineer">
                    <user-select v-model="bid.responsible_engineer_user_id" :user_id="bid.responsible_engineer_user_id" end_point="users/" :name="'responsible'" />
                  </b-field>
                </div>
              </div>
            </b-field>
          </div>`

**Expected behavior**
Vue Select to not display the key value of the second instance of the component but show the defined label field

**Screenshots**

On Render:

![image](https://user-images.githubusercontent.com/48888686/62635247-94d48f00-b8f4-11e9-8176-d0d72635507f.png)

Data of first instances:

![image](https://user-images.githubusercontent.com/48888686/62635437-e67d1980-b8f4-11e9-8fd8-ec694e68e66f.png)

Data of second instsance:

![image](https://user-images.githubusercontent.com/48888686/62635471-feed3400-b8f4-11e9-8d7e-2491d3963928.png)

Desired Output (by re-selecting):

![image](https://user-images.githubusercontent.com/48888686/62635552-23e1a700-b8f5-11e9-83df-1210a29f5b36.png)

**Desktop:**
OS: Windows 10
Browser: Brave 0.67.123

**Comment by doits** [comment]
Does #914 fix it?

**Comment by robertmarney** [comment]
@doits - Yes!  wish I saw that PR an hour ago :)

Thanks for your help!
