### ISSUE TITLE
on-search is fired on selection

### ISSUE THREAD

**Issue by geri777** [sagalbot/vue-select#933]
**Describe the bug**
Whenever I select a value, the @search function is called with an empty string as argument. This causes the option list to change. 
In further versions, when the option list will be reactive, this will lead to the following problem: Depending on the data, the new list might have no corresponding element to the selected value and thus just the record ID is displayed.

**To Reproduce**
1. Go to https://plnkr.co/edit/ITy2eHO4gc1JU8UjIrmG?p=preview
2. Enter a letter (eg. "a" or "c") and select a list item
3. The id of the option is displayed instead of the label

**Expected behavior**
V-Select should clear the search, but not fire an on-search event on item selection

**Additional context**
This bug is more a beauty mistake - until you try a branch with reactive list options.
https://github.com/sagalbot/vue-select/pull/914

**Comment by doits** [comment]
I'm not sure if *not* triggering an empty `search` event is the correct solution generally, but since it does maybe you can work around it by simply *not* searching if the `search` is blank in your case?

```typescript
    // <vue-select @search="fetchSelectOptions">

    fetchSelectOptions(search?: string) {
      if (!search) {
        return
      }

      // ... fetch options ...
    }
```

This will make it keep the options of the last search until it is searched again.

**Comment by geri777** [comment]
Yes, that's my workaround indeed. :-)

**Comment by doits** [comment]
Just found out this still triggers the bug if another search is made which does not include the current value but no new option is selected. So it only fixes it partially.

**Comment by geri777** [comment]
Oooh - you are right - I did not think of this scenario. I think the selected value should be decoupled from the option list. Your workaround might be too complex and error prone for everyday use.

**Comment by babymechanic** [comment]
Hi, I am facing this issue as well. I noticed that the `open` flag is set to false before emitting the event. I used this work around as was wondering if this will work?
```typescript 
getData: async function (term: string, loading: (done: boolean) => void) {
      if (!(<any>this.$refs.select).open) return;
```
