### ISSUE TITLE
need createoption example

### ISSUE THREAD

**Issue by Dontorpedo** [sagalbot/vue-select#952]
hello,

its not clear to me how to create new options if needed.. can someone provide an example?

i have some predefined options, but want the user also let create new options..

thanks..

**Comment by safinn** [comment]
Had the same requirement. The taggable prop helped. https://vue-select.org/guide/values.html#tagging

**Comment by prashant1k99** [comment]
What if we want to customize the vue, like: `User Option - Create new Option` Custom handling or want to display the creatOption only when the ajax fetched options don't match the value
.
