### ISSUE TITLE
Can't to select option if another option is already selected

### ISSUE THREAD

**Issue by maxttor** [sagalbot/vue-select#954]
**Describe the bug**
I choose an option. It is successfully selected. I choose another option - it is not selected. To select another item, I must first delete the previous one.

**Expected behavior**
I select a new option - it automatically replaces the previous one

**Screenshots**
Screencast: https://drive.google.com/file/d/1mCjVBOBa2O-XVWKJFPpzZ3y9MxM45afY/view

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version: 77.0.3865.90

**Comment by maxttor** [comment]
I missed https://vue-select.org/api/props.html#getoptionlabel

**Comment by alistairwebcom** [comment]
Hey i dont understand its possible you help me? he doesn't work for me.

my vue
` 
<v-select :options="options" :filterable="false" @search="onSearch" style="width: 200px;" v-model="number.customer">
                    <template slot="no-options">
                        Recherche client
                    </template>

                    <template slot="option" slot-scope="option">
                        <div class="d-center">
                            <div v-if="option.SocieteStyle" v-html="option.SocieteStyle"></div>
                            <span v-if="option.NomStyle" v-html="option.NomStyle"></span>
                            <span v-if="option.PrenomStyle" v-html="option.PrenomStyle"></span>
                        </div>
                    </template>
                    <template slot="selected-option" slot-scope="option">
                        <div class="selected d-center">
                            <div v-if="option.Societe" v-html="option.Societe"></div>
                            <span v-if="option.Nom" v-html="option.Nom"></span>
                            <span v-if="option.Prenom" v-html="option.Prenom"></span>
                        </div>
                    </template>
                </v-select>
`

my script
`onSearch(search, loading){
                if(search.length >= 3){
                    loading(true);
                    this.search(loading, search, this);
                }
            },
            search: _.debounce((loading, search, vm) => {

                let formData = new FormData();
                formData.append('search', search);

                axios.post('customer', formData)
                    .then(data => {
                        console.log(data.data);
                        vm.options = data.data
                        loading(false);
                    })
                    .catch(function(error) {
                        console.log(error);
                        loading(false);
                    });
            }, 500)`


Thank's
