### ISSUE TITLE
changing the model programmatically doesn't change the select element while using :reduce 

### ISSUE THREAD

**Issue by DvirH** [sagalbot/vue-select#957]
**Describe the bug**
When using options as array of objects, and reduce to get the value,
changing the model programmaticaly, doesn't change the select option to the relevant one

**To Reproduce**
1. create a v-select element with options as array of objects (key-value)
2. add a reduce property to get the value
3. create a method that set the v-model to the last item of the options array

**Expected behavior**
the select box should select the relevant option

**Comment by pyr0hu** [comment]
Have you tried the latest 3.2.0 version? That should include a bugfix regarding reduce and v-model.

**Comment by DvirH** [comment]
I didn't try, Thanks for notice.
