### ISSUE TITLE
vue-select validation with vee-validate v3

### ISSUE THREAD

**Issue by gdhnz** [sagalbot/vue-select#995]
More of a support issue but I'm struggling to workout how to get validation working on a vue-select using vee-validate.

vee-validate is now up to version 3 with significant changes over v2 so what used to work with vue-select, no longer does.

https://codepen.io/gdhnz/pen/MWWPoOm?editors=1010

Anyone out there managed to get validation to work?

**Comment by gdhnz** [comment]
It works if you select an element and then clear it but it doesn't work if you click in and then click out without selecting anything.

**Comment by vuong2017** [comment]
You can use temporary with 2 options:
1. Create a component BasicSelect 
- You just need to add events @search:blur="function"
<v-select
     ...
    @search:blur="$emit('blur')"
 />

<ValidationProvider name="city" rules="required" v-slot="{errors}" tag="div" class="form-group">
       <BasicSelect 
        :class="{'is-invalid': !!errors.length}" 
        :..
        />
        <div class="invalid-feedback">{{ errors[0] }}</div>
</ValidationProvider>
2. use the event @search:blur 
 <ValidationObserver ref="form" tag="form">
   <ValidationProvider name="city" rules="required" v-slot="{errors}" tag="div" class="form-group">
     <v-select
     :class="{'is-invalid': !!errors.length}" 
     ...
    @search:blur="blur"
     />
     <div class="invalid-feedback">{{ errors[0] }}</div>
    </ValidationProvider>
</ValidationObserver>
computed:
computedForm() {
    return this.$refs.form;
}
methods: 
blur() {
this.computedForm.refs.city.validate();
}

**Comment by gdhnz** [comment]
That's brilliant.  Thanks.  Have updated the CodePen with your second suggestion.

**Comment by lvar** [comment]
Is there a way of validate this example on submit form ? not on blur or input

**Comment by alirezamires** [comment]
> Is there a way of validate this example on submit form ? not on blur or input

 You should add validate rule for object and empty object like this:

extend('vselect' ,{
    validate : value => {
        return value !== undefined && value !== null && Object.keys(value).length > 0;
    }
}); 
and then set on your Provider like this:

<ValidationProvider v-slot="{ errors }"
                      :rules="{required: required ,vselect:true}">
